name: Project Tests
on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      EMAILUSERNAME: ${{ secrets.EMAILUSERNAME }}
      MYAWESOMESECRET: ${{ secrets.MYAWESOMESECRET }}
      PROD_MAIL_PASSWORD: ${{ secrets.EMAILPASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and test with Maven
        run: mvn -B clean verify --file pom.xml
